Repository DEV-dsm/DMG_BackEnd, pull requests merged in 2023-08, with the labels that each got.

#32 (#31) ✨ :: feat :: add a new func CreateMessage
  package-lock.json
  package.json
  src/app.module.ts
  src/chat/chat.controller.ts
  src/chat/chat.gateway.ts
  src/chat/chat.module.ts
  src/chat/chat.service.ts
  src/chat/dto/createMessage.dto.ts
  src/chat/entity/chatting.entity.ts
  src/chat/entity/group.entity.ts
  src/chat/entity/groupMapping.entity.ts
  src/main.ts
  src/user/entities/user.entity.ts
  src/user/user.service.ts
Labels: 기능 수정, 기능 추가

#48 (#47) ✨ :: feat :: getGroupInfo
  package-lock.json
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
  src/chat/entity/groupMapping.entity.ts
  src/user/entities/user.entity.ts
Labels: 기능 추가

#50 (#49) ✨ :: feat :: newGroupManager
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
  src/user/entities/user.entity.ts
Labels: 기능 수정, 기능 추가

#54 (#53) ✨ :: feat :: new func createGroupPeople
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
  src/chat/dto/createGroupPeople.dto.ts
Labels: 기능 추가

#56 (#55) ✨ :: feat :: new func inviteMember
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
  src/chat/dto/inviteMember.dto.ts
Labels: 기능 추가

#58 (#57) ✨ :: feat :: new func goneGroup
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
  src/chat/entity/chatting.entity.ts
  src/chat/entity/group.entity.ts
  src/chat/entity/groupMapping.entity.ts
  src/user/entities/question.entity.ts
  src/user/entities/student.entity.ts
  src/user/entities/teacher.entity.ts
  src/user/entities/user.entity.ts
Labels: 기능 추가

#60 (#59) ✨ :: feat :: updateGroupInfo
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
  src/chat/dto/updateGroupInfo.dto.ts
  src/profile/profile.controller.ts
Labels: 기능 추가

#62 (#61) ✨ :: feat :: new func setChatToNotice
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
  src/chat/entity/chatting.entity.ts
Labels: 기능 추가

#68 (#67) 👀 :: chore :: update the logic
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
Labels: 기능 수정

#70 (#69) ✨ :: feat :: new func getOutMember
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
Labels: 기능 수정, 기능 추가

#73 (#72) ✨ :: feat :: new func readMessage
  src/app.module.ts
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
  src/chat/entity/chatting.entity.ts
Labels: 기능 추가

#74 (#71) 🐛 :: fix :: with createNewGroup
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
Labels: 버그

#76 (#75) ✨ :; feat :: new func choosePrRepo
  package-lock.json
  package.json
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
Labels: 기능 추가
