Repository DEV-dsm/DMG_BackEnd, pull requests merged in 2023-12, with the labels that each got.

#112 (#111) ✨ :: feat :: new func uploadFile
  package-lock.json
  package.json
  src/app.module.ts
  src/upload/upload.controller.ts
  src/upload/upload.module.ts
  src/upload/upload.service.ts
Labels: 기능 추가

#114 👀 :: chore :: update UploadFile
  src/upload/upload.service.ts
Labels: 기능 수정

#110 (#109) 👀 :: chore :: 채팅방 생성하기 API 통합
  .github/workflows/CICD.yml
  README.md
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
  src/chat/dto/createGroup.dto.ts
  src/chat/dto/createGroupPeople.dto.ts
  src/chat/dto/createGroupPerson.dto.ts
  src/chat/entity/group.entity.ts
Labels: 기능 수정

#118 (#117) ✍ :: style & refactor :: update return style
  src/chat/chat.controller.ts
  src/profile/profile.controller.ts
  src/upload/upload.controller.ts
  src/user/user.controller.ts
Labels: 리팩토링

#120 (#119) 👀 :: chore :: modify update profile
  src/profile/dto/searchProfile.dto.ts
  src/profile/dto/updateStudentProfile.dto.ts
  src/profile/dto/updateTeacherProfile.dto.ts
  src/profile/profile.controller.ts
  src/profile/profile.service.ts
Labels: 기능 수정, 리팩토링

#122 🐛 :: fix :: fixed QueryBuilder and added an annotation
  dump.rdb
  src/chat/chat.service.ts
Labels: 버그
