Repository DEV-dsm/DMG_BackEnd, pull requests merged in 2023-07, with the labels that each got.

#5 (#4)💡 :: setting :: setting Entity
  package-lock.json
  package.json
  src/app.module.ts
  src/user/entities/student.entity.ts
  src/user/entities/teacher.entity.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: 프로젝트 세팅

#7 ✨ :: feat :: createAcc
  package-lock.json
  package.json
  src/user/dto/createAcc.dev.dto.ts
  src/user/dto/password.dto.ts
  src/user/dto/token.dto.ts
  src/user/dto/userPayload.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: 기능 추가

#9 ✨ :: feat :: patchPW
  src/main.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: 기능 추가

#11 👀 :: chore :: patchPW
  src/user/user.service.ts
Labels: 기능 수정

#14 (#12) Create login
  src/user/dto/login-user.dto.ts
  src/user/entities/student.entity.ts
  src/user/entities/teacher.entity.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: 기능 수정, 기능 추가

#16 👀 :: chore :: 자잘한 수정
  src/user/entities/student.entity.ts
  src/user/entities/teacher.entity.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: 기능 수정

#18 ✨ :: feat :: create func question
  src/user/dto/question.dto.ts
  src/user/entities/question.entity.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: 기능 추가

#20 (#19) ✨ :: feat :: sendEmail
  package-lock.json
  package.json
  src/mail/mail.service.ts
  src/user/dto/send-email.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: 기능 추가

#22 (#21) ✨ :: feat :: new func findPW
  src/user/entities/question.entity.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: 기능 수정, 기능 추가

#24 (#23) ✨ :: feat :: new func updateStudentProfile
  src/mail/mail.service.ts
  src/user/dto/createAcc.dev.dto.ts
  src/user/dto/login-user.dto.ts
  src/user/dto/password.dto.ts
  src/user/dto/question.dto.ts
  src/user/dto/send-email.dto.ts
  src/user/dto/studentProfile.dto.ts
  src/user/dto/token.dto.ts
  src/user/dto/userPayload.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: 기능 수정, 기능 추가

#26 (#25) 👀 :: chore :: update a logic of validateRefresh
  src/user/dto/studentProfile.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: 기능 수정, 기능 추가

#28 (#27) ✨ :: feat :: add a new func getStudentProfile
  src/app.module.ts
  src/profile/profile.controller.ts
  src/profile/profile.module.ts
  src/profile/profile.service.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: 기능 수정, 기능 추가

#30 (#29) ✨ :: feat :: new func getStudentProfileList
  src/profile/profile.controller.ts
  src/profile/profile.service.ts
  src/user/entities/student.entity.ts
  src/user/user.module.ts
Labels: 기능 수정, 기능 추가

#34 (#33) Update teacher profile
  src/app.module.ts
  src/mail/mail.service.ts
  src/profile/profile.controller.ts
  src/profile/profile.service.ts
  src/user/dto/update-teacherProfile.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: 기능 수정, 기능 추가

#36 (#35) Get teacher profile
  src/profile/profile.controller.ts
  src/profile/profile.service.ts
  src/user/dto/loginUser.dto.ts
  src/user/dto/teacherProfile.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: 기능 추가

#38 (#37) 👀 :: chore :: linked with Slack
  package-lock.json
  package.json
  src/app.module.ts
  src/config/slack.config.ts
  src/user/user.service.ts
Labels: 기능 수정

#40 (#39) ✨ :: feat :: new func getTeacherProfileList
  src/profile/profile.controller.ts
  src/profile/profile.service.ts
Labels: 기능 추가

#42 (#41) 👀 :: chore :: logic updated from TypeORM Method to QueryBuilder
  src/profile/profile.service.ts
Labels: 기능 수정

#44 (#43) ✨ :: feat :: Search profile
  package-lock.json
  package.json
  src/main.ts
  src/profile/profile.controller.ts
  src/profile/profile.service.ts
  src/user/dto/createAcc.dev.dto.ts
  src/user/dto/searchProfile.dto.ts
  src/user/dto/studentProfile.dto.ts
  src/user/entities/student.entity.ts
Labels: 기능 수정, 기능 추가

#46 (#45) 👀 :: chore :: Verify email
  src/mail/mail.service.ts
  src/profile/profile.controller.ts
  src/user/dto/searchProfile.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: 기능 수정, 기능 추가
