Repository DEV-dsm/DMG_BackEnd, pull requests merged in 2023-10, with the labels that each got.

#97 (#96) 👀 :: chore :: Update code
  .dockerignore
  .gitignore
  Dockerfile
  package-lock.json
  package.json
  src/app.module.ts
  src/main.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: 기능 수정

#99 (#98) 👀 :: chore :: fix github pr bot account's id
  src/chat/chat.service.ts
Labels: 기능 수정

#102 (#101) 🐛 :: bug :: fixed bug
  package-lock.json
  package.json
  src/chat/chat.service.ts
Labels: 기능 수정, 버그

#104 (#105) 💡 :: setting :: CICD 파일 생성
  .github/workflow/CICD.yml
Labels: 프로젝트 세팅

#108 (#107) 👀 :: chore :: fixed response
  src/chat/chat.service.ts
  src/profile/profile.service.ts
Labels: 기능 수정
