Repository DEV-dsm/DMG_BackEnd, pull requests merged in 2023-09, with the labels that each got.

#78 (#77) Auto stash before merge of "main" and "origin/main"
  src/chat/chat.service.ts
  src/chat/entity/chatting.entity.ts
  src/chat/entity/group.entity.ts
  src/chat/entity/groupMapping.entity.ts
Labels: 기능 수정

#82 (#81) ✨ :: feat :: new func getChatList
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
Labels: 기능 추가

#85 (#84) 🌱 :: add :: create docker-compose file
  docker-compose.yaml
Labels: 프로젝트 세팅

#87 (#86) ✨ :: feat :: new func createAnnounce
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
  src/chat/dto/repo.dto.ts
Labels: 기능 추가

#89 (#88) 🐛 :: fix :: fixed function
  src/user/user.service.ts
Labels: 기능 수정, 버그

#93 (#92)✨ :: feat :: getGithubPR
  src/chat/chat.controller.ts
  src/chat/chat.service.ts
Labels: 기능 추가

#91 (#90) 👀 :: chore :: patchStudentProfile
  src/profile/profile.service.ts
  src/user/dto/studentProfile.dto.ts
Labels: 기능 수정

#95 (#94) 🚑 :: hotfix :: validateRefresh
  src/profile/profile.service.ts
  src/user/user.service.ts
Labels: 버그
